CREATE TABLE worker (
    ID BIGSERIAL PRIMARY KEY, 
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),  
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900), 
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')), 
    SALARY INTEGER CHECK (SALARY >= 100 AND SALARY <= 100000)
	);


CREATE TABLE client (
    ID BIGSERIAL PRIMARY KEY,  
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)  
);


CREATE TABLE project (
    ID BIGSERIAL PRIMARY KEY, 
    CLIENT_ID BIGINT REFERENCES client(ID),  
    START_DATE DATE, 
    FINISH_DATE DATE 
);


CREATE TABLE project_worker (
    PROJECT_ID BIGINT REFERENCES project(ID),
    WORKER_ID BIGINT REFERENCES worker(ID), 
    PRIMARY KEY (PROJECT_ID, WORKER_ID)  
);
